/**
 * Constants and error handling utilities
 */

export const ErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  // 通用错误码（兼容已有代码）
  BAD_REQUEST: "BAD_REQUEST",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  // Medal Template 相关错误码
  MEDAL_NAME_INVALID: "MEDAL_NAME_INVALID",
  MEDAL_NAME_TOO_SHORT: "MEDAL_NAME_TOO_SHORT",
  MEDAL_NAME_TOO_LONG: "MEDAL_NAME_TOO_LONG",
  MEDAL_ICON_REQUIRED: "MEDAL_ICON_REQUIRED",
  MEDAL_INVALID_BORDER_STYLE: "MEDAL_INVALID_BORDER_STYLE",
  MEDAL_INVALID_LEVEL_MODE: "MEDAL_INVALID_LEVEL_MODE",
  MEDAL_INVALID_LEVEL_COUNT: "MEDAL_INVALID_LEVEL_COUNT",
  MEDAL_INVALID_TIER_COLORS: "MEDAL_INVALID_TIER_COLORS",
  MEDAL_THRESHOLD_INVALID: "MEDAL_THRESHOLD_INVALID",
  MEDAL_THRESHOLD_NOT_ASCENDING: "MEDAL_THRESHOLD_NOT_ASCENDING",
  MEDAL_TEMPLATE_NOT_FOUND: "MEDAL_TEMPLATE_NOT_FOUND",
  MEDAL_TEMPLATE_IN_USE: "MEDAL_TEMPLATE_IN_USE",
} as const;

export function createErrorResponse(
  code: string,
  message: string,
  details?: any
) {
  return {
    success: false,
    code,
    message,
    ...(details !== undefined && { details }),
  };
}

export function createSuccessResponse<T>(data: T) {
  return {
    success: true,
    data,
  };
}
